# Generated by Django 6.0.6 on 2026-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaircareProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('suitable', models.BooleanField(default=True)),
                ('hair_type', models.CharField(max_length=200)),
                ('hair_pattern', models.CharField(max_length=200)),
                ('scalp_condition', models.CharField(max_length=200)),
                ('product_link', models.URLField()),
                ('image', models.ImageField(upload_to='haircare-products')),
            ],
        ),
        migrations.CreateModel(
            name='SkincareProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('skin_type', models.CharField(max_length=200)),
                ('primary_concern', models.CharField(max_length=200)),
                ('secondary_concern', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('product_link', models.URLField()),
                ('image', models.ImageField(upload_to='skincare-products')),
            ],
        ),
    ]
