# Generated by Django 6.0.6 on 2026-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareproducts',
            name='suitable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skincareproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skincare-products'),
        ),
    ]
